# site settings
title: Ariella
subtitle: Cheskis-Gold
email: acheskisgold@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city: New York
state: NY
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/ariellacg/
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/ariella.cg/
linkedin_url: https://www.linkedin.com/in/ariellacheskisgold/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
